// Life domains and representative tasks.
// 200 tasks across 20 domains, each testing the model on a specific real-world need.
// Every task has complexity and optional context for richer prompt rendering.

export interface DomainTask {
  domain: string;
  task: string;
  complexity: 'easy' | 'medium' | 'hard';
  context?: string;
}

export const DOMAIN_TASKS: DomainTask[] = [
  // ── Personal Finance (1-15) ──────────────────────────────────────
  { domain: 'finance', task: 'Create a monthly budget for someone earning $5,000/month', complexity: 'easy' },
  { domain: 'finance', task: 'Explain compound interest with a concrete example', complexity: 'easy' },
  { domain: 'finance', task: 'List the differences between a checking and savings account', complexity: 'easy' },
  { domain: 'finance', task: 'Compare the pros and cons of a Roth IRA vs Traditional IRA for a 30-year-old', complexity: 'medium' },
  { domain: 'finance', task: 'Create an emergency fund savings plan from zero to $10,000', complexity: 'medium' },
  { domain: 'finance', task: 'Explain how dollar-cost averaging works with a stock example', complexity: 'medium' },
  { domain: 'finance', task: 'Build a debt payoff strategy using avalanche and snowball methods for 4 different debts', complexity: 'hard' },
  { domain: 'finance', task: 'Evaluate whether refinancing a mortgage at 5.5% to 4.2% is worth closing costs of $6,000', complexity: 'hard' },
  { domain: 'finance', task: 'Design a tax-efficient withdrawal strategy for a retiree with 401k, Roth, and brokerage accounts', complexity: 'hard' },
  { domain: 'finance', task: 'Calculate the total cost of a 30-year mortgage at $350,000 with 6.5% interest', complexity: 'medium' },

  // ── Health & Wellness (16-30) ────────────────────────────────────
  { domain: 'health', task: 'Explain the difference between aerobic and anaerobic exercise', complexity: 'easy' },
  { domain: 'health', task: 'List 5 evidence-based strategies for improving sleep quality', complexity: 'easy' },
  { domain: 'health', task: 'Describe what BMI measures and its limitations', complexity: 'easy' },
  { domain: 'health', task: 'Suggest a 7-day meal plan for someone with type 2 diabetes', complexity: 'medium' },
  { domain: 'health', task: 'Create a stress management plan that incorporates CBT techniques', complexity: 'medium' },
  { domain: 'health', task: 'Outline a beginner-friendly 5K training program over 8 weeks', complexity: 'medium' },
  { domain: 'health', task: 'Design a 12-week progressive strength training program for a beginner', complexity: 'hard' },
  { domain: 'health', task: 'Compare intermittent fasting protocols (16:8, 5:2, OMAD) with evidence for each', complexity: 'hard' },
  { domain: 'health', task: 'Create a comprehensive postpartum recovery plan covering physical and mental health', complexity: 'hard' },
  { domain: 'health', task: 'Explain how to read a nutrition facts label with a real example', complexity: 'easy' },

  // ── Software Engineering (31-50) ─────────────────────────────────
  { domain: 'code', task: 'Write a function to check if a string is a valid palindrome', complexity: 'easy' },
  { domain: 'code', task: 'Explain the difference between concurrency and parallelism with examples', complexity: 'easy' },
  { domain: 'code', task: 'Write a function that flattens a nested array to any depth', complexity: 'easy' },
  { domain: 'code', task: 'Explain what a closure is in JavaScript with a practical example', complexity: 'easy' },
  { domain: 'code', task: 'Design a REST API schema for a task management application', complexity: 'medium' },
  { domain: 'code', task: 'Write a debounce function with proper TypeScript types', complexity: 'medium' },
  { domain: 'code', task: 'Explain the CAP theorem and give a real-world database example for each tradeoff', complexity: 'medium' },
  { domain: 'code', task: 'Implement a basic LRU cache with O(1) get and put operations', complexity: 'medium' },
  { domain: 'code', task: 'Implement a rate limiter using the token bucket algorithm with sliding window', complexity: 'hard' },
  { domain: 'code', task: 'Refactor a monolithic function into smaller composable units following SOLID principles', complexity: 'hard', context: 'function processOrder(order) { /* validates, calculates tax, applies discount, charges payment, sends email, updates inventory */ }' },
  { domain: 'code', task: 'Design a pub/sub event system with typed events and wildcard subscriptions', complexity: 'hard' },
  { domain: 'code', task: 'Write a recursive descent parser for basic arithmetic expressions (+-*/)', complexity: 'hard' },
  { domain: 'code', task: 'Compare React useEffect cleanup patterns for subscriptions, timers, and fetch requests', complexity: 'medium' },
  { domain: 'code', task: 'Write a retry wrapper function with exponential backoff and jitter', complexity: 'medium' },
  { domain: 'code', task: 'Design the database schema for a multi-tenant SaaS application', complexity: 'hard' },
  { domain: 'code', task: 'Write unit tests for a shopping cart total calculation with discounts and taxes', complexity: 'medium' },
  { domain: 'code', task: 'Explain the difference between SQL joins (inner, left, right, full, cross) with diagrams', complexity: 'easy' },
  { domain: 'code', task: 'Implement a trie data structure with insert, search, and prefix matching', complexity: 'hard' },
  { domain: 'code', task: 'Write a middleware function for Express.js that logs request duration and status', complexity: 'easy' },
  { domain: 'code', task: 'Design an API versioning strategy comparing URL path, header, and query param approaches', complexity: 'medium' },

  // ── Writing & Communication (51-65) ──────────────────────────────
  { domain: 'writing', task: 'Write a professional email declining a meeting invitation', complexity: 'easy' },
  { domain: 'writing', task: 'Rewrite this sentence to be more concise: "Due to the fact that we are currently experiencing a situation where..."', complexity: 'easy' },
  { domain: 'writing', task: 'Write a thank-you note after a job interview', complexity: 'easy' },
  { domain: 'writing', task: 'Draft a persuasive cover letter for a career change from teaching to tech', complexity: 'medium' },
  { domain: 'writing', task: 'Write a technical blog post outline about microservices vs monoliths', complexity: 'medium' },
  { domain: 'writing', task: 'Create a press release for a startup product launch', complexity: 'medium' },
  { domain: 'writing', task: 'Write an incident postmortem report for a 2-hour database outage', complexity: 'medium', context: 'Root cause: a migration script dropped an index on the users table during peak traffic. Impact: 12,000 failed requests, $8,000 estimated revenue loss.' },
  { domain: 'writing', task: 'Create an executive summary for a quarterly business review with 3 key metrics declining', complexity: 'hard' },
  { domain: 'writing', task: 'Write a technical RFC for migrating from REST to GraphQL', complexity: 'hard' },
  { domain: 'writing', task: 'Draft a crisis communication email to customers about a data breach', complexity: 'hard' },
  { domain: 'writing', task: 'Write a compelling product description for a noise-cancelling headphone', complexity: 'easy' },
  { domain: 'writing', task: 'Create a style guide for API documentation', complexity: 'medium' },
  { domain: 'writing', task: 'Write a resignation letter that maintains good relationships', complexity: 'easy' },
  { domain: 'writing', task: 'Draft a proposal for a remote work policy', complexity: 'hard' },
  { domain: 'writing', task: 'Write 3 versions of an app store description optimized for different audiences', complexity: 'hard' },

  // ── Education & Learning (66-80) ─────────────────────────────────
  { domain: 'education', task: 'Explain quantum entanglement to a 12-year-old', complexity: 'easy' },
  { domain: 'education', task: 'Summarize the key ideas of cognitive load theory', complexity: 'easy' },
  { domain: 'education', task: 'Explain the Pythagorean theorem with a real-world application', complexity: 'easy' },
  { domain: 'education', task: 'Create a study plan for learning calculus in 3 months', complexity: 'medium' },
  { domain: 'education', task: 'Design a lesson plan for teaching recursion to first-time programmers', complexity: 'medium' },
  { domain: 'education', task: 'Explain the scientific method using a chocolate chip cookie experiment', complexity: 'medium' },
  { domain: 'education', task: 'Design a rubric for evaluating argumentative essays at a college level', complexity: 'hard' },
  { domain: 'education', task: 'Build a curriculum for a 6-week intro to machine learning course', complexity: 'hard' },
  { domain: 'education', task: 'Create a Socratic dialogue that teaches the concept of supply and demand', complexity: 'hard' },
  { domain: 'education', task: 'Compare Bloom\'s Taxonomy and Webb\'s Depth of Knowledge frameworks', complexity: 'medium' },
  { domain: 'education', task: 'Write 5 multiple-choice questions testing understanding of photosynthesis', complexity: 'easy' },
  { domain: 'education', task: 'Explain how neural networks learn using an analogy a high schooler would understand', complexity: 'medium' },
  { domain: 'education', task: 'Design a project-based learning unit on climate change for 10th graders', complexity: 'hard' },
  { domain: 'education', task: 'Create flashcards for the 20 most important concepts in microeconomics', complexity: 'easy' },
  { domain: 'education', task: 'Write a worked example for solving a system of linear equations', complexity: 'medium' },

  // ── Legal & Compliance (81-93) ───────────────────────────────────
  { domain: 'legal', task: 'Explain the difference between copyright and trademark', complexity: 'easy' },
  { domain: 'legal', task: 'List the key elements needed in a freelance contract', complexity: 'easy' },
  { domain: 'legal', task: 'Explain what "at-will employment" means in the US', complexity: 'easy' },
  { domain: 'legal', task: 'Draft a basic non-disclosure agreement outline', complexity: 'medium' },
  { domain: 'legal', task: 'Summarize the key requirements of the CAN-SPAM Act', complexity: 'medium' },
  { domain: 'legal', task: 'Explain the difference between an LLC and a sole proprietorship', complexity: 'medium' },
  { domain: 'legal', task: 'Analyze the GDPR implications of storing user analytics data across EU and US servers', complexity: 'hard' },
  { domain: 'legal', task: 'Compare LLC vs S-Corp tax treatment for a solo consultant earning $150K', complexity: 'hard' },
  { domain: 'legal', task: 'Draft a terms of service outline for a SaaS product', complexity: 'hard' },
  { domain: 'legal', task: 'Explain the concept of fair use with 4 concrete examples', complexity: 'medium' },
  { domain: 'legal', task: 'Create a GDPR data processing agreement checklist', complexity: 'hard' },
  { domain: 'legal', task: 'Explain the difference between a patent and a trade secret', complexity: 'easy' },
  { domain: 'legal', task: 'Outline the steps to register a trademark in the US', complexity: 'medium' },

  // ── Data Analysis (94-108) ───────────────────────────────────────
  { domain: 'data', task: 'Explain what a p-value means in plain language', complexity: 'easy' },
  { domain: 'data', task: 'Describe when to use median vs mean for summarizing data', complexity: 'easy' },
  { domain: 'data', task: 'Explain the difference between correlation and causation with examples', complexity: 'easy' },
  { domain: 'data', task: 'Design an A/B test plan for a website checkout flow change', complexity: 'medium' },
  { domain: 'data', task: 'Write a SQL query to find the top 5 customers by lifetime value with at least 3 orders in the last 6 months', complexity: 'hard' },
  { domain: 'data', task: 'Explain Type I and Type II errors using a medical testing analogy', complexity: 'medium' },
  { domain: 'data', task: 'Create a data pipeline architecture for processing 10M events/day from IoT sensors', complexity: 'hard' },
  { domain: 'data', task: 'Design a dashboard layout for monitoring key SaaS metrics (MRR, churn, NPS)', complexity: 'medium' },
  { domain: 'data', task: 'Write a data quality checklist for validating a customer dataset before analysis', complexity: 'medium' },
  { domain: 'data', task: 'Explain how a random forest algorithm works to a business stakeholder', complexity: 'medium' },
  { domain: 'data', task: 'Build a cohort analysis framework for measuring user retention', complexity: 'hard' },
  { domain: 'data', task: 'Calculate sample size needed for an A/B test with 5% significance and 80% power', complexity: 'hard' },
  { domain: 'data', task: 'Explain what overfitting is and 3 techniques to prevent it', complexity: 'easy' },
  { domain: 'data', task: 'Write a Python script to clean a CSV file with missing values, duplicates, and inconsistent formatting', complexity: 'hard' },
  { domain: 'data', task: 'Compare SQL window functions (ROW_NUMBER, RANK, DENSE_RANK) with examples', complexity: 'medium' },

  // ── Project Management (109-123) ─────────────────────────────────
  { domain: 'project_mgmt', task: 'Write 3 user stories for a login feature', complexity: 'easy' },
  { domain: 'project_mgmt', task: 'Define acceptance criteria for a password reset feature', complexity: 'easy' },
  { domain: 'project_mgmt', task: 'Write a standup update summarizing yesterday, today, and blockers', complexity: 'easy' },
  { domain: 'project_mgmt', task: 'Create a risk assessment matrix for a software migration project', complexity: 'medium' },
  { domain: 'project_mgmt', task: 'Design a sprint planning template for a team of 6 engineers', complexity: 'medium' },
  { domain: 'project_mgmt', task: 'Write a project charter for building a customer feedback portal', complexity: 'medium' },
  { domain: 'project_mgmt', task: 'Build a sprint retrospective analysis from these data points and recommend process changes', complexity: 'hard', context: 'Velocity dropped 30% over 3 sprints. Bug count rose from 5 to 18. Team satisfaction survey shows "unclear requirements" as top complaint.' },
  { domain: 'project_mgmt', task: 'Create a stakeholder communication plan for a 6-month platform rewrite', complexity: 'hard' },
  { domain: 'project_mgmt', task: 'Design a capacity planning model for a growing engineering team', complexity: 'hard' },
  { domain: 'project_mgmt', task: 'Create a decision log template for architectural choices', complexity: 'medium' },
  { domain: 'project_mgmt', task: 'Write a RACI matrix for a product launch involving engineering, design, marketing, and support', complexity: 'medium' },
  { domain: 'project_mgmt', task: 'Build a prioritization framework comparing RICE, MoSCoW, and weighted scoring', complexity: 'hard' },
  { domain: 'project_mgmt', task: 'Create an onboarding checklist for a new team member joining mid-sprint', complexity: 'easy' },
  { domain: 'project_mgmt', task: 'Design a release management process for a team shipping weekly', complexity: 'hard' },
  { domain: 'project_mgmt', task: 'Write acceptance criteria for an e-commerce search feature with filters, sorting, and pagination', complexity: 'medium' },

  // ── Creative & Design (124-138) ──────────────────────────────────
  { domain: 'creative', task: 'Generate 5 tagline options for an eco-friendly water bottle brand', complexity: 'easy' },
  { domain: 'creative', task: 'Brainstorm 10 names for a podcast about behavioral economics', complexity: 'easy' },
  { domain: 'creative', task: 'Write a haiku about debugging code', complexity: 'easy' },
  { domain: 'creative', task: 'Design a color palette and typography system for a fintech startup', complexity: 'medium' },
  { domain: 'creative', task: 'Create a mood board description for a luxury wellness spa brand', complexity: 'medium' },
  { domain: 'creative', task: 'Write 3 different opening paragraphs for a mystery novel', complexity: 'medium' },
  { domain: 'creative', task: 'Write a short story (300 words) with a twist ending about time travel', complexity: 'hard' },
  { domain: 'creative', task: 'Create a brand voice guide covering tone, vocabulary, and do/don\'t examples', complexity: 'hard' },
  { domain: 'creative', task: 'Design a game mechanic for a mobile app that teaches vocabulary', complexity: 'hard' },
  { domain: 'creative', task: 'Write a 30-second radio ad script for a local pizza restaurant', complexity: 'easy' },
  { domain: 'creative', task: 'Create a character profile for the antagonist of a sci-fi thriller', complexity: 'medium' },
  { domain: 'creative', task: 'Design a user onboarding flow with 5 screens for a meditation app', complexity: 'hard' },
  { domain: 'creative', task: 'Write a limerick about machine learning', complexity: 'easy' },
  { domain: 'creative', task: 'Create a worldbuilding document for a fantasy setting with 3 factions', complexity: 'hard' },
  { domain: 'creative', task: 'Design an infographic layout for explaining how the internet works', complexity: 'medium' },

  // ── Science & Research (139-153) ─────────────────────────────────
  { domain: 'science', task: 'Explain CRISPR gene editing in simple terms', complexity: 'easy' },
  { domain: 'science', task: 'Compare and contrast mitosis and meiosis', complexity: 'easy' },
  { domain: 'science', task: 'Explain what dark matter is and why scientists think it exists', complexity: 'easy' },
  { domain: 'science', task: 'Design an experiment to test whether a new fertilizer improves tomato yield', complexity: 'medium' },
  { domain: 'science', task: 'Explain the greenhouse effect and its role in climate change', complexity: 'medium' },
  { domain: 'science', task: 'Describe how mRNA vaccines work compared to traditional vaccines', complexity: 'medium' },
  { domain: 'science', task: 'Write an abstract for a research paper on transformer attention mechanisms', complexity: 'hard' },
  { domain: 'science', task: 'Propose a methodology for measuring the carbon footprint of cloud computing workloads', complexity: 'hard' },
  { domain: 'science', task: 'Design a peer review checklist for evaluating machine learning research papers', complexity: 'hard' },
  { domain: 'science', task: 'Explain the double-slit experiment and its implications for quantum mechanics', complexity: 'medium' },
  { domain: 'science', task: 'Compare 3 renewable energy sources (solar, wind, geothermal) on cost, scalability, and reliability', complexity: 'hard' },
  { domain: 'science', task: 'Explain how CRISPR-Cas9 differs from older gene editing techniques like TALENs and ZFNs', complexity: 'hard' },
  { domain: 'science', task: 'Write a research question and hypothesis for studying screen time effects on children', complexity: 'medium' },
  { domain: 'science', task: 'Explain entropy using a deck of cards analogy', complexity: 'easy' },
  { domain: 'science', task: 'Describe the water cycle with quantitative data about each stage', complexity: 'medium' },

  // ── Daily Life / Practical (154-168) ─────────────────────────────
  { domain: 'practical', task: 'Create a packing checklist for a 5-day business trip', complexity: 'easy' },
  { domain: 'practical', task: 'Write step-by-step instructions for changing a car tire', complexity: 'easy' },
  { domain: 'practical', task: 'List what to check before signing an apartment lease', complexity: 'easy' },
  { domain: 'practical', task: 'Plan a weekly grocery list and cooking schedule for a family of 4 on a $150 budget', complexity: 'medium' },
  { domain: 'practical', task: 'Create a first aid kit checklist with quantities and replacement schedule', complexity: 'medium' },
  { domain: 'practical', task: 'Write a guide for setting up a home office ergonomically', complexity: 'medium' },
  { domain: 'practical', task: 'Create a home maintenance schedule covering HVAC, plumbing, electrical, and exterior for all 4 seasons', complexity: 'hard' },
  { domain: 'practical', task: 'Design a moving checklist with timeline from 8 weeks before to 1 week after', complexity: 'hard' },
  { domain: 'practical', task: 'Create a disaster preparedness plan for a family of 4 covering fire, earthquake, and power outage', complexity: 'hard' },
  { domain: 'practical', task: 'Write a comparison of 3 meal delivery services on cost, variety, and nutrition', complexity: 'medium' },
  { domain: 'practical', task: 'Create a car buying checklist from research to final purchase', complexity: 'medium' },
  { domain: 'practical', task: 'Design a weekly cleaning schedule for a 3-bedroom house', complexity: 'easy' },
  { domain: 'practical', task: 'Write instructions for hosting a dinner party for 8 people', complexity: 'medium' },
  { domain: 'practical', task: 'Create a pet care routine for a new puppy covering first 6 months', complexity: 'hard' },
  { domain: 'practical', task: 'List 10 things to do within 30 days of moving to a new city', complexity: 'easy' },

  // ── Negotiation & Persuasion (169-178) ───────────────────────────
  { domain: 'negotiation', task: 'Write 3 different ways to ask for a deadline extension', complexity: 'easy' },
  { domain: 'negotiation', task: 'Draft a message asking a landlord to fix a recurring maintenance issue', complexity: 'easy' },
  { domain: 'negotiation', task: 'Draft a salary negotiation email after receiving an offer 15% below expectation', complexity: 'medium' },
  { domain: 'negotiation', task: 'Write a persuasive proposal to convince management to adopt a new tool', complexity: 'medium' },
  { domain: 'negotiation', task: 'Create a framework for evaluating and responding to a vendor price increase', complexity: 'hard' },
  { domain: 'negotiation', task: 'Draft a counter-offer response to a client who wants 40% scope increase with no budget change', complexity: 'hard' },
  { domain: 'negotiation', task: 'Write an escalation email that is firm but professional about a missed SLA', complexity: 'medium' },
  { domain: 'negotiation', task: 'Create a negotiation prep sheet for buying a used car', complexity: 'medium' },
  { domain: 'negotiation', task: 'Design a stakeholder influence map and engagement strategy for a controversial project', complexity: 'hard' },
  { domain: 'negotiation', task: 'Write a diplomatic response to negative feedback from a client', complexity: 'easy' },

  // ── Ethics & Decision Making (179-188) ───────────────────────────
  { domain: 'ethics', task: 'List the pros and cons of remote work vs office work', complexity: 'easy' },
  { domain: 'ethics', task: 'Explain the trolley problem and its relevance to AI decision-making', complexity: 'easy' },
  { domain: 'ethics', task: 'Create a decision matrix for choosing between two job offers', complexity: 'medium' },
  { domain: 'ethics', task: 'Analyze the ethical implications of personalized pricing algorithms', complexity: 'medium' },
  { domain: 'ethics', task: 'Analyze the ethical considerations of using AI for hiring decisions', complexity: 'hard' },
  { domain: 'ethics', task: 'Write an ethical impact assessment for a facial recognition deployment in a school', complexity: 'hard' },
  { domain: 'ethics', task: 'Compare utilitarian and deontological approaches to data privacy', complexity: 'medium' },
  { domain: 'ethics', task: 'Create a framework for evaluating the societal impact of a new technology', complexity: 'hard' },
  { domain: 'ethics', task: 'Write a code of ethics for an AI startup with 5 core principles', complexity: 'medium' },
  { domain: 'ethics', task: 'Analyze the dual-use dilemma of open-sourcing powerful AI models', complexity: 'hard' },

  // ── Marketing & Growth (189-200) ─────────────────────────────────
  { domain: 'marketing', task: 'Write 3 variations of ad copy for a productivity app', complexity: 'easy' },
  { domain: 'marketing', task: 'Write a tweet thread (5 tweets) announcing a new product feature', complexity: 'easy' },
  { domain: 'marketing', task: 'Design a content calendar for a B2B SaaS company\'s first month on social media', complexity: 'medium' },
  { domain: 'marketing', task: 'Create an email drip sequence (5 emails) for onboarding new SaaS users', complexity: 'medium' },
  { domain: 'marketing', task: 'Create a go-to-market strategy for launching a developer tool in a crowded market', complexity: 'hard' },
  { domain: 'marketing', task: 'Design a referral program with incentive structure and viral coefficient targets', complexity: 'hard' },
  { domain: 'marketing', task: 'Write a competitive analysis comparing 3 project management tools', complexity: 'medium' },
  { domain: 'marketing', task: 'Create a landing page copy framework with headline, subhead, features, social proof, and CTA', complexity: 'medium' },
  { domain: 'marketing', task: 'Design a customer journey map from awareness to advocacy for a subscription box service', complexity: 'hard' },
  { domain: 'marketing', task: 'Write SEO-optimized meta descriptions for 5 product category pages', complexity: 'easy' },
  { domain: 'marketing', task: 'Create a brand positioning statement using the "For [target], [brand] is the [category] that [benefit]" framework', complexity: 'medium' },
  { domain: 'marketing', task: 'Design an influencer marketing campaign strategy for a DTC skincare brand', complexity: 'hard' },

  // ── Troubleshooting & Debugging (201-212) ────────────────────────
  { domain: 'debugging', task: 'Explain what a 502 Bad Gateway error means and common causes', complexity: 'easy' },
  { domain: 'debugging', task: 'List the most common reasons a Docker container exits immediately', complexity: 'easy' },
  { domain: 'debugging', task: 'Explain what causes a "Cannot read properties of undefined" error in JavaScript', complexity: 'easy' },
  { domain: 'debugging', task: 'Diagnose why a Node.js application has a memory leak', complexity: 'medium', context: 'Heap usage grows linearly from 200MB to 1.2GB over 6 hours before crashing with OOM.' },
  { domain: 'debugging', task: 'Debug why a React component re-renders on every state change even when props haven\'t changed', complexity: 'medium' },
  { domain: 'debugging', task: 'Troubleshoot why a cron job runs but produces no output', complexity: 'medium' },
  { domain: 'debugging', task: 'Create a systematic debugging checklist for a production API returning intermittent 500 errors', complexity: 'hard' },
  { domain: 'debugging', task: 'Diagnose a database deadlock from this error log and propose a fix', complexity: 'hard', context: 'ERROR: deadlock detected. Process 1234 waits for ShareLock on transaction 5678; Process 5678 waits for ShareLock on transaction 1234.' },
  { domain: 'debugging', task: 'Write a runbook for debugging high CPU usage on a Linux server', complexity: 'hard' },
  { domain: 'debugging', task: 'Explain how to use Chrome DevTools to diagnose a slow web page', complexity: 'medium' },
  { domain: 'debugging', task: 'Diagnose why CSS grid items overflow their container', complexity: 'easy' },
  { domain: 'debugging', task: 'Create a decision tree for diagnosing common Kubernetes pod failures', complexity: 'hard' },

  // ── Career Development (213-224) ─────────────────────────────────
  { domain: 'career', task: 'List 5 questions to ask in a job interview', complexity: 'easy' },
  { domain: 'career', task: 'Write a LinkedIn summary for a mid-career software engineer', complexity: 'easy' },
  { domain: 'career', task: 'Create a personal SWOT analysis template for career planning', complexity: 'easy' },
  { domain: 'career', task: 'Create a 90-day onboarding plan for a new senior engineer', complexity: 'medium' },
  { domain: 'career', task: 'Design a mentorship program structure for a 50-person engineering team', complexity: 'medium' },
  { domain: 'career', task: 'Write a self-review for an annual performance evaluation covering 3 achievements and 2 growth areas', complexity: 'medium' },
  { domain: 'career', task: 'Design a career growth framework with levels, competencies, and promotion criteria for an engineering org', complexity: 'hard' },
  { domain: 'career', task: 'Create a skills gap analysis for transitioning from backend to full-stack development', complexity: 'hard' },
  { domain: 'career', task: 'Design a technical interview loop for hiring senior engineers (4 rounds)', complexity: 'hard' },
  { domain: 'career', task: 'Write a 5-year career development plan for someone transitioning into engineering management', complexity: 'hard' },
  { domain: 'career', task: 'Create a portfolio review checklist for a frontend developer job application', complexity: 'medium' },
  { domain: 'career', task: 'Write constructive feedback for a junior developer who struggles with code reviews', complexity: 'medium' },

  // ── DevOps & Infrastructure (225-234) ────────────────────────────
  { domain: 'devops', task: 'Write a Dockerfile for a Node.js application with multi-stage build', complexity: 'easy' },
  { domain: 'devops', task: 'Explain the difference between horizontal and vertical scaling', complexity: 'easy' },
  { domain: 'devops', task: 'Create a CI/CD pipeline configuration for a monorepo with 3 services', complexity: 'medium' },
  { domain: 'devops', task: 'Design a monitoring and alerting strategy for a microservices architecture', complexity: 'medium' },
  { domain: 'devops', task: 'Write a Terraform module for deploying an AWS Lambda function with API Gateway', complexity: 'hard' },
  { domain: 'devops', task: 'Design a blue-green deployment strategy for a stateful application', complexity: 'hard' },
  { domain: 'devops', task: 'Create a Kubernetes deployment manifest with health checks, resource limits, and autoscaling', complexity: 'hard' },
  { domain: 'devops', task: 'Explain the 12-factor app methodology and which factors matter most for containerized apps', complexity: 'medium' },
  { domain: 'devops', task: 'Write a bash script to rotate log files older than 30 days', complexity: 'easy' },
  { domain: 'devops', task: 'Design a secrets management strategy comparing HashiCorp Vault, AWS Secrets Manager, and environment variables', complexity: 'hard' },

  // ── Psychology & Behavior (235-244) ──────────────────────────────
  { domain: 'psychology', task: 'Explain the Dunning-Kruger effect with a workplace example', complexity: 'easy' },
  { domain: 'psychology', task: 'List 5 cognitive biases that affect decision-making at work', complexity: 'easy' },
  { domain: 'psychology', task: 'Design a habit tracker based on the principles from Atomic Habits', complexity: 'medium' },
  { domain: 'psychology', task: 'Explain how to use the Eisenhower Matrix for time management with examples', complexity: 'medium' },
  { domain: 'psychology', task: 'Create a conflict resolution framework for workplace disagreements', complexity: 'medium' },
  { domain: 'psychology', task: 'Analyze why people procrastinate using temporal motivation theory', complexity: 'hard' },
  { domain: 'psychology', task: 'Design a behavioral nudge strategy to increase employee 401k enrollment', complexity: 'hard' },
  { domain: 'psychology', task: 'Compare 3 therapeutic approaches (CBT, DBT, ACT) for anxiety management', complexity: 'hard' },
  { domain: 'psychology', task: 'Explain the concept of psychological safety and 3 ways to build it in a team', complexity: 'medium' },
  { domain: 'psychology', task: 'Write a guided meditation script for managing pre-presentation anxiety', complexity: 'medium' },

  // ── Product Design & UX (245-256) ────────────────────────────────
  { domain: 'product', task: 'Write a usability test script for testing a checkout flow', complexity: 'medium' },
  { domain: 'product', task: 'Create a user persona for a fitness tracking app', complexity: 'easy' },
  { domain: 'product', task: 'List Nielsen\'s 10 usability heuristics with a violation example for each', complexity: 'medium' },
  { domain: 'product', task: 'Design an information architecture for a recipe sharing website', complexity: 'medium' },
  { domain: 'product', task: 'Write a PRD (product requirements document) for a notification preferences feature', complexity: 'hard' },
  { domain: 'product', task: 'Create a competitive UX audit comparing 3 note-taking apps', complexity: 'hard' },
  { domain: 'product', task: 'Design an accessibility checklist based on WCAG 2.1 AA standards', complexity: 'hard' },
  { domain: 'product', task: 'Explain the difference between UX and UI with concrete examples', complexity: 'easy' },
  { domain: 'product', task: 'Create a user journey map for booking a flight on a travel website', complexity: 'medium' },
  { domain: 'product', task: 'Write microcopy for 5 common error states (404, form validation, timeout, permission denied, empty state)', complexity: 'medium' },
  { domain: 'product', task: 'Design an A/B test plan for a new onboarding flow', complexity: 'hard' },
  { domain: 'product', task: 'Create a design system documentation template covering colors, spacing, components, and patterns', complexity: 'hard' },
];
